# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            single camera time travel jokes about dogs
tagline:          'a thing'
description:      'things that interest me'
url:              http://robertoLewis.github.io
baseurl:          /

author:
  name:           'Roberto Lewis'
  url:            https://robertolewis.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/RobertoLewis/RobertoLewis.github.io
