# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            muttering to myself
tagline:          'a thing'
description:      'words about things'
url:              http://RobertoLewis.github.io
baseurl:          /

author:
  name:           'Roberto Lewis'
  url:            https://robertolewis.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/RobertoLewis/RobertoLewis.github.io
